export const allPlayersData = {
  data: [
    {
      assists: 36,
      evGoals: 7,
      evPoints: 32,
      faceoffWinPct: 0.47495,
      gameWinningGoals: 3,
      gamesPlayed: 30,
      goals: 10,
      lastName: "MacKinnon",
      otGoals: 1,
      penaltyMinutes: 18,
      playerId: 8477492,
      plusMinus: 4,
      points: 46,
      pointsPerGame: 1.53333,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 14,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.08403,
      shootsCatches: "R",
      shots: 119,
      skaterFullName: "Nathan MacKinnon",
      teamAbbrevs: "COL",
      timeOnIcePerGame: 1394.1,
    },
    {
      assists: 25,
      evGoals: 15,
      evPoints: 33,
      faceoffWinPct: 0.0,
      gameWinningGoals: 4,
      gamesPlayed: 27,
      goals: 18,
      lastName: "Kaprizov",
      otGoals: 1,
      penaltyMinutes: 8,
      playerId: 8478864,
      plusMinus: 21,
      points: 43,
      pointsPerGame: 1.59259,
      positionCode: "L",
      ppGoals: 3,
      ppPoints: 10,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.2,
      shootsCatches: "L",
      shots: 90,
      skaterFullName: "Kirill Kaprizov",
      teamAbbrevs: "MIN",
      timeOnIcePerGame: 1349.8888,
    },
    {
      assists: 29,
      evGoals: 7,
      evPoints: 24,
      faceoffWinPct: 0.4375,
      gameWinningGoals: 5,
      gamesPlayed: 28,
      goals: 14,
      lastName: "Necas",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8480039,
      plusMinus: 5,
      points: 43,
      pointsPerGame: 1.53571,
      positionCode: "C",
      ppGoals: 7,
      ppPoints: 19,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.2,
      shootsCatches: "R",
      shots: 70,
      skaterFullName: "Martin Necas",
      teamAbbrevs: "CAR",
      timeOnIcePerGame: 1108.5357,
    },
    {
      assists: 24,
      evGoals: 13,
      evPoints: 29,
      faceoffWinPct: 0.52343,
      gameWinningGoals: 5,
      gamesPlayed: 30,
      goals: 18,
      lastName: "Rantanen",
      otGoals: 0,
      penaltyMinutes: 20,
      playerId: 8478420,
      plusMinus: 3,
      points: 42,
      pointsPerGame: 1.4,
      positionCode: "R",
      ppGoals: 5,
      ppPoints: 13,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.21176,
      shootsCatches: "L",
      shots: 85,
      skaterFullName: "Mikko Rantanen",
      teamAbbrevs: "COL",
      timeOnIcePerGame: 1353.4333,
    },
    {
      assists: 20,
      evGoals: 9,
      evPoints: 22,
      faceoffWinPct: 0.42081,
      gameWinningGoals: 1,
      gamesPlayed: 29,
      goals: 19,
      lastName: "Reinhart",
      otGoals: 0,
      penaltyMinutes: 4,
      playerId: 8477933,
      plusMinus: 9,
      points: 39,
      pointsPerGame: 1.34482,
      positionCode: "C",
      ppGoals: 6,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 4,
      shPoints: 5,
      shootingPct: 0.24675,
      shootsCatches: "R",
      shots: 77,
      skaterFullName: "Sam Reinhart",
      teamAbbrevs: "FLA",
      timeOnIcePerGame: 1230.7241,
    },
    {
      assists: 30,
      evGoals: 8,
      evPoints: 27,
      faceoffWinPct: 0.4896,
      gameWinningGoals: 0,
      gamesPlayed: 28,
      goals: 9,
      lastName: "Eichel",
      otGoals: 0,
      penaltyMinutes: 4,
      playerId: 8478403,
      plusMinus: 12,
      points: 39,
      pointsPerGame: 1.39285,
      positionCode: "C",
      ppGoals: 1,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.1125,
      shootsCatches: "R",
      shots: 80,
      skaterFullName: "Jack Eichel",
      teamAbbrevs: "VGK",
      timeOnIcePerGame: 1248.1428,
    },
    {
      assists: 18,
      evGoals: 16,
      evPoints: 29,
      faceoffWinPct: 0.57227,
      gameWinningGoals: 6,
      gamesPlayed: 28,
      goals: 20,
      lastName: "Draisaitl",
      otGoals: 3,
      penaltyMinutes: 10,
      playerId: 8477934,
      plusMinus: 15,
      points: 38,
      pointsPerGame: 1.35714,
      positionCode: "C",
      ppGoals: 4,
      ppPoints: 9,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.25974,
      shootsCatches: "L",
      shots: 77,
      skaterFullName: "Leon Draisaitl",
      teamAbbrevs: "EDM",
      timeOnIcePerGame: 1278.8571,
    },
    {
      assists: 24,
      evGoals: 9,
      evPoints: 28,
      faceoffWinPct: 0.48648,
      gameWinningGoals: 2,
      gamesPlayed: 25,
      goals: 14,
      lastName: "McDavid",
      otGoals: 0,
      penaltyMinutes: 8,
      playerId: 8478402,
      plusMinus: 8,
      points: 38,
      pointsPerGame: 1.52,
      positionCode: "C",
      ppGoals: 5,
      ppPoints: 10,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.15555,
      shootsCatches: "L",
      shots: 90,
      skaterFullName: "Connor McDavid",
      teamAbbrevs: "EDM",
      timeOnIcePerGame: 1287.44,
    },
    {
      assists: 25,
      evGoals: 12,
      evPoints: 22,
      faceoffWinPct: null,
      gameWinningGoals: 3,
      gamesPlayed: 24,
      goals: 13,
      lastName: "Kucherov",
      otGoals: 0,
      penaltyMinutes: 2,
      playerId: 8476453,
      plusMinus: 6,
      points: 38,
      pointsPerGame: 1.58333,
      positionCode: "R",
      ppGoals: 1,
      ppPoints: 16,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.14606,
      shootsCatches: "L",
      shots: 89,
      skaterFullName: "Nikita Kucherov",
      teamAbbrevs: "TBL",
      timeOnIcePerGame: 1295.875,
    },
    {
      assists: 25,
      evGoals: 8,
      evPoints: 20,
      faceoffWinPct: 0.0,
      gameWinningGoals: 0,
      gamesPlayed: 31,
      goals: 13,
      lastName: "Bratt",
      otGoals: 0,
      penaltyMinutes: 12,
      playerId: 8479407,
      plusMinus: 6,
      points: 38,
      pointsPerGame: 1.2258,
      positionCode: "L",
      ppGoals: 4,
      ppPoints: 17,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 1,
      shootingPct: 0.16455,
      shootsCatches: "L",
      shots: 79,
      skaterFullName: "Jesper Bratt",
      teamAbbrevs: "NJD",
      timeOnIcePerGame: 1106.3548,
    },
    {
      assists: 28,
      evGoals: 5,
      evPoints: 22,
      faceoffWinPct: 0.22222,
      gameWinningGoals: 2,
      gamesPlayed: 28,
      goals: 10,
      lastName: "Marner",
      otGoals: 1,
      penaltyMinutes: 4,
      playerId: 8478483,
      plusMinus: 5,
      points: 38,
      pointsPerGame: 1.35714,
      positionCode: "R",
      ppGoals: 4,
      ppPoints: 15,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 1,
      shootingPct: 0.14492,
      shootsCatches: "R",
      shots: 69,
      skaterFullName: "Mitch Marner",
      teamAbbrevs: "TOR",
      timeOnIcePerGame: 1304.9285,
    },
    {
      assists: 20,
      evGoals: 9,
      evPoints: 26,
      faceoffWinPct: 0.0,
      gameWinningGoals: 3,
      gamesPlayed: 30,
      goals: 16,
      lastName: "Connor",
      otGoals: 1,
      penaltyMinutes: 15,
      playerId: 8478398,
      plusMinus: 8,
      points: 36,
      pointsPerGame: 1.2,
      positionCode: "L",
      ppGoals: 6,
      ppPoints: 9,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 1,
      shootingPct: 0.15841,
      shootsCatches: "L",
      shots: 101,
      skaterFullName: "Kyle Connor",
      teamAbbrevs: "WPG",
      timeOnIcePerGame: 1208.0333,
    },
    {
      assists: 27,
      evGoals: 4,
      evPoints: 20,
      faceoffWinPct: null,
      gameWinningGoals: 2,
      gamesPlayed: 30,
      goals: 9,
      lastName: "Makar",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8480069,
      plusMinus: 3,
      points: 36,
      pointsPerGame: 1.2,
      positionCode: "D",
      ppGoals: 4,
      ppPoints: 15,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 1,
      shootingPct: 0.0989,
      shootsCatches: "R",
      shots: 91,
      skaterFullName: "Cale Makar",
      teamAbbrevs: "COL",
      timeOnIcePerGame: 1512.0333,
    },
    {
      assists: 24,
      evGoals: 7,
      evPoints: 18,
      faceoffWinPct: 0.36532,
      gameWinningGoals: 3,
      gamesPlayed: 31,
      goals: 11,
      lastName: "Hughes",
      otGoals: 1,
      penaltyMinutes: 2,
      playerId: 8481559,
      plusMinus: 5,
      points: 35,
      pointsPerGame: 1.12903,
      positionCode: "C",
      ppGoals: 4,
      ppPoints: 17,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.10185,
      shootsCatches: "L",
      shots: 108,
      skaterFullName: "Jack Hughes",
      teamAbbrevs: "NJD",
      timeOnIcePerGame: 1243.1935,
    },
    {
      assists: 26,
      evGoals: 7,
      evPoints: 23,
      faceoffWinPct: 0.54988,
      gameWinningGoals: 0,
      gamesPlayed: 27,
      goals: 9,
      lastName: "Strome",
      otGoals: 0,
      penaltyMinutes: 10,
      playerId: 8478440,
      plusMinus: 16,
      points: 35,
      pointsPerGame: 1.29629,
      positionCode: "C",
      ppGoals: 2,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.21428,
      shootsCatches: "L",
      shots: 42,
      skaterFullName: "Dylan Strome",
      teamAbbrevs: "WSH",
      timeOnIcePerGame: 1055.0,
    },
    {
      assists: 18,
      evGoals: 13,
      evPoints: 22,
      faceoffWinPct: 0.49884,
      gameWinningGoals: 5,
      gamesPlayed: 30,
      goals: 16,
      lastName: "Scheifele",
      otGoals: 1,
      penaltyMinutes: 21,
      playerId: 8476460,
      plusMinus: 3,
      points: 34,
      pointsPerGame: 1.13333,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.23529,
      shootsCatches: "R",
      shots: 68,
      skaterFullName: "Mark Scheifele",
      teamAbbrevs: "WPG",
      timeOnIcePerGame: 1232.4666,
    },
    {
      assists: 19,
      evGoals: 8,
      evPoints: 25,
      faceoffWinPct: 0.35483,
      gameWinningGoals: 2,
      gamesPlayed: 29,
      goals: 15,
      lastName: "Konecny",
      otGoals: 0,
      penaltyMinutes: 35,
      playerId: 8478439,
      plusMinus: 0,
      points: 34,
      pointsPerGame: 1.17241,
      positionCode: "R",
      ppGoals: 6,
      ppPoints: 8,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 1,
      shootingPct: 0.18518,
      shootsCatches: "R",
      shots: 81,
      skaterFullName: "Travis Konecny",
      teamAbbrevs: "PHI",
      timeOnIcePerGame: 1271.5517,
    },
    {
      assists: 19,
      evGoals: 10,
      evPoints: 23,
      faceoffWinPct: 0.0,
      gameWinningGoals: 1,
      gamesPlayed: 27,
      goals: 15,
      lastName: "Panarin",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8478550,
      plusMinus: -3,
      points: 34,
      pointsPerGame: 1.25925,
      positionCode: "L",
      ppGoals: 5,
      ppPoints: 11,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.16483,
      shootsCatches: "R",
      shots: 91,
      skaterFullName: "Artemi Panarin",
      teamAbbrevs: "NYR",
      timeOnIcePerGame: 1193.3703,
    },
    {
      assists: 24,
      evGoals: 9,
      evPoints: 22,
      faceoffWinPct: 0.3409,
      gameWinningGoals: 0,
      gamesPlayed: 27,
      goals: 10,
      lastName: "StÃ¼tzle",
      otGoals: 0,
      penaltyMinutes: 14,
      playerId: 8482116,
      plusMinus: 5,
      points: 34,
      pointsPerGame: 1.25925,
      positionCode: "C",
      ppGoals: 1,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.17857,
      shootsCatches: "L",
      shots: 56,
      skaterFullName: "Tim StÃ¼tzle",
      teamAbbrevs: "OTT",
      timeOnIcePerGame: 1217.3703,
    },
    {
      assists: 24,
      evGoals: 6,
      evPoints: 21,
      faceoffWinPct: 0.57733,
      gameWinningGoals: 4,
      gamesPlayed: 28,
      goals: 8,
      lastName: "Kopitar",
      otGoals: 0,
      penaltyMinutes: 0,
      playerId: 8471685,
      plusMinus: 15,
      points: 32,
      pointsPerGame: 1.14285,
      positionCode: "C",
      ppGoals: 2,
      ppPoints: 10,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 1,
      shootingPct: 0.24242,
      shootsCatches: "L",
      shots: 33,
      skaterFullName: "Anze Kopitar",
      teamAbbrevs: "LAK",
      timeOnIcePerGame: 1154.1785,
    },
    {
      assists: 25,
      evGoals: 6,
      evPoints: 19,
      faceoffWinPct: null,
      gameWinningGoals: 1,
      gamesPlayed: 27,
      goals: 7,
      lastName: "Hughes",
      otGoals: 0,
      penaltyMinutes: 19,
      playerId: 8480800,
      plusMinus: 9,
      points: 32,
      pointsPerGame: 1.18518,
      positionCode: "D",
      ppGoals: 1,
      ppPoints: 13,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.07954,
      shootsCatches: "L",
      shots: 88,
      skaterFullName: "Quinn Hughes",
      teamAbbrevs: "VAN",
      timeOnIcePerGame: 1501.4444,
    },
    {
      assists: 19,
      evGoals: 11,
      evPoints: 25,
      faceoffWinPct: 0.38461,
      gameWinningGoals: 1,
      gamesPlayed: 26,
      goals: 12,
      lastName: "Hagel",
      otGoals: 0,
      penaltyMinutes: 24,
      playerId: 8479542,
      plusMinus: 12,
      points: 31,
      pointsPerGame: 1.1923,
      positionCode: "L",
      ppGoals: 0,
      ppPoints: 4,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 2,
      shootingPct: 0.16438,
      shootsCatches: "L",
      shots: 73,
      skaterFullName: "Brandon Hagel",
      teamAbbrevs: "TBL",
      timeOnIcePerGame: 1287.923,
    },
    {
      assists: 12,
      evGoals: 8,
      evPoints: 18,
      faceoffWinPct: 0.5,
      gameWinningGoals: 3,
      gamesPlayed: 22,
      goals: 18,
      lastName: "Point",
      otGoals: 2,
      penaltyMinutes: 2,
      playerId: 8478010,
      plusMinus: 4,
      points: 30,
      pointsPerGame: 1.36363,
      positionCode: "C",
      ppGoals: 10,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.36734,
      shootsCatches: "R",
      shots: 49,
      skaterFullName: "Brayden Point",
      teamAbbrevs: "TBL",
      timeOnIcePerGame: 1174.409,
    },
    {
      assists: 19,
      evGoals: 9,
      evPoints: 16,
      faceoffWinPct: 0.0,
      gameWinningGoals: 3,
      gamesPlayed: 28,
      goals: 11,
      lastName: "Raymond",
      otGoals: 1,
      penaltyMinutes: 6,
      playerId: 8482078,
      plusMinus: 1,
      points: 30,
      pointsPerGame: 1.07142,
      positionCode: "L",
      ppGoals: 1,
      ppPoints: 13,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 1,
      shootingPct: 0.18333,
      shootsCatches: "R",
      shots: 60,
      skaterFullName: "Lucas Raymond",
      teamAbbrevs: "DET",
      timeOnIcePerGame: 1160.4285,
    },
    {
      assists: 20,
      evGoals: 6,
      evPoints: 19,
      faceoffWinPct: 0.47704,
      gameWinningGoals: 0,
      gamesPlayed: 29,
      goals: 10,
      lastName: "Granlund",
      otGoals: 0,
      penaltyMinutes: 12,
      playerId: 8475798,
      plusMinus: -2,
      points: 30,
      pointsPerGame: 1.03448,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 10,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 1,
      shootingPct: 0.12195,
      shootsCatches: "L",
      shots: 82,
      skaterFullName: "Mikael Granlund",
      teamAbbrevs: "SJS",
      timeOnIcePerGame: 1250.6551,
    },
    {
      assists: 20,
      evGoals: 5,
      evPoints: 18,
      faceoffWinPct: 0.0,
      gameWinningGoals: 1,
      gamesPlayed: 24,
      goals: 10,
      lastName: "Tkachuk",
      otGoals: 0,
      penaltyMinutes: 22,
      playerId: 8479314,
      plusMinus: -1,
      points: 30,
      pointsPerGame: 1.25,
      positionCode: "L",
      ppGoals: 5,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.14084,
      shootsCatches: "L",
      shots: 71,
      skaterFullName: "Matthew Tkachuk",
      teamAbbrevs: "FLA",
      timeOnIcePerGame: 1086.0416,
    },
    {
      assists: 23,
      evGoals: 5,
      evPoints: 16,
      faceoffWinPct: 0.55303,
      gameWinningGoals: 3,
      gamesPlayed: 28,
      goals: 7,
      lastName: "Aho",
      otGoals: 2,
      penaltyMinutes: 22,
      playerId: 8478427,
      plusMinus: -5,
      points: 30,
      pointsPerGame: 1.07142,
      positionCode: "C",
      ppGoals: 2,
      ppPoints: 13,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 1,
      shootingPct: 0.09589,
      shootsCatches: "L",
      shots: 73,
      skaterFullName: "Sebastian Aho",
      teamAbbrevs: "CAR",
      timeOnIcePerGame: 1202.6071,
    },
    {
      assists: 16,
      evGoals: 6,
      evPoints: 18,
      faceoffWinPct: 0.50322,
      gameWinningGoals: 2,
      gamesPlayed: 27,
      goals: 13,
      lastName: "Tkachuk",
      otGoals: 1,
      penaltyMinutes: 50,
      playerId: 8480801,
      plusMinus: -1,
      points: 29,
      pointsPerGame: 1.07407,
      positionCode: "L",
      ppGoals: 7,
      ppPoints: 11,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.11111,
      shootsCatches: "L",
      shots: 117,
      skaterFullName: "Brady Tkachuk",
      teamAbbrevs: "OTT",
      timeOnIcePerGame: 1106.4074,
    },
    {
      assists: 17,
      evGoals: 9,
      evPoints: 18,
      faceoffWinPct: 0.53303,
      gameWinningGoals: 3,
      gamesPlayed: 27,
      goals: 12,
      lastName: "Duchene",
      otGoals: 0,
      penaltyMinutes: 4,
      playerId: 8475168,
      plusMinus: 13,
      points: 29,
      pointsPerGame: 1.07407,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 11,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.26086,
      shootsCatches: "L",
      shots: 46,
      skaterFullName: "Matt Duchene",
      teamAbbrevs: "DAL",
      timeOnIcePerGame: 985.7777,
    },
    {
      assists: 19,
      evGoals: 9,
      evPoints: 21,
      faceoffWinPct: 0.49406,
      gameWinningGoals: 3,
      gamesPlayed: 28,
      goals: 10,
      lastName: "Suzuki",
      otGoals: 2,
      penaltyMinutes: 4,
      playerId: 8480018,
      plusMinus: 2,
      points: 29,
      pointsPerGame: 1.03571,
      positionCode: "C",
      ppGoals: 1,
      ppPoints: 8,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.16393,
      shootsCatches: "R",
      shots: 61,
      skaterFullName: "Nick Suzuki",
      teamAbbrevs: "MTL",
      timeOnIcePerGame: 1180.8214,
    },
    {
      assists: 20,
      evGoals: 4,
      evPoints: 14,
      faceoffWinPct: 0.63851,
      gameWinningGoals: 0,
      gamesPlayed: 21,
      goals: 9,
      lastName: "Barkov",
      otGoals: 0,
      penaltyMinutes: 4,
      playerId: 8477493,
      plusMinus: 3,
      points: 29,
      pointsPerGame: 1.38095,
      positionCode: "C",
      ppGoals: 4,
      ppPoints: 11,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 4,
      shootingPct: 0.18,
      shootsCatches: "L",
      shots: 50,
      skaterFullName: "Aleksander Barkov",
      teamAbbrevs: "FLA",
      timeOnIcePerGame: 1209.7142,
    },
    {
      assists: 20,
      evGoals: 6,
      evPoints: 18,
      faceoffWinPct: null,
      gameWinningGoals: 2,
      gamesPlayed: 28,
      goals: 9,
      lastName: "Werenski",
      otGoals: 1,
      penaltyMinutes: 15,
      playerId: 8478460,
      plusMinus: 9,
      points: 29,
      pointsPerGame: 1.03571,
      positionCode: "D",
      ppGoals: 3,
      ppPoints: 10,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 1,
      shootingPct: 0.09375,
      shootsCatches: "L",
      shots: 96,
      skaterFullName: "Zach Werenski",
      teamAbbrevs: "CBJ",
      timeOnIcePerGame: 1566.4642,
    },
    {
      assists: 11,
      evGoals: 10,
      evPoints: 15,
      faceoffWinPct: 0.50588,
      gameWinningGoals: 5,
      gamesPlayed: 28,
      goals: 17,
      lastName: "Nylander",
      otGoals: 0,
      penaltyMinutes: 12,
      playerId: 8477939,
      plusMinus: -3,
      points: 28,
      pointsPerGame: 1.0,
      positionCode: "R",
      ppGoals: 7,
      ppPoints: 13,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.17894,
      shootsCatches: "R",
      shots: 95,
      skaterFullName: "William Nylander",
      teamAbbrevs: "TOR",
      timeOnIcePerGame: 1167.1428,
    },
    {
      assists: 14,
      evGoals: 11,
      evPoints: 22,
      faceoffWinPct: 0.46153,
      gameWinningGoals: 0,
      gamesPlayed: 28,
      goals: 14,
      lastName: "Kempe",
      otGoals: 0,
      penaltyMinutes: 16,
      playerId: 8477960,
      plusMinus: 16,
      points: 28,
      pointsPerGame: 1.0,
      positionCode: "R",
      ppGoals: 2,
      ppPoints: 5,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 1,
      shootingPct: 0.17948,
      shootsCatches: "L",
      shots: 78,
      skaterFullName: "Adrian Kempe",
      teamAbbrevs: "LAK",
      timeOnIcePerGame: 1136.5714,
    },
    {
      assists: 15,
      evGoals: 12,
      evPoints: 27,
      faceoffWinPct: 0.33333,
      gameWinningGoals: 2,
      gamesPlayed: 28,
      goals: 13,
      lastName: "Barbashev",
      otGoals: 0,
      penaltyMinutes: 2,
      playerId: 8477964,
      plusMinus: 13,
      points: 28,
      pointsPerGame: 1.0,
      positionCode: "C",
      ppGoals: 1,
      ppPoints: 1,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.27659,
      shootsCatches: "L",
      shots: 47,
      skaterFullName: "Ivan Barbashev",
      teamAbbrevs: "VGK",
      timeOnIcePerGame: 1015.5,
    },
    {
      assists: 16,
      evGoals: 8,
      evPoints: 20,
      faceoffWinPct: 0.4923,
      gameWinningGoals: 5,
      gamesPlayed: 28,
      goals: 12,
      lastName: "Boldy",
      otGoals: 1,
      penaltyMinutes: 23,
      playerId: 8481557,
      plusMinus: 8,
      points: 28,
      pointsPerGame: 1.0,
      positionCode: "L",
      ppGoals: 4,
      ppPoints: 8,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.11214,
      shootsCatches: "L",
      shots: 107,
      skaterFullName: "Matt Boldy",
      teamAbbrevs: "MIN",
      timeOnIcePerGame: 1188.3928,
    },
    {
      assists: 18,
      evGoals: 6,
      evPoints: 22,
      faceoffWinPct: 0.33333,
      gameWinningGoals: 2,
      gamesPlayed: 30,
      goals: 10,
      lastName: "Pastrnak",
      otGoals: 1,
      penaltyMinutes: 20,
      playerId: 8477956,
      plusMinus: -6,
      points: 28,
      pointsPerGame: 0.93333,
      positionCode: "R",
      ppGoals: 4,
      ppPoints: 6,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.08333,
      shootsCatches: "R",
      shots: 120,
      skaterFullName: "David Pastrnak",
      teamAbbrevs: "BOS",
      timeOnIcePerGame: 1186.4666,
    },
    {
      assists: 19,
      evGoals: 4,
      evPoints: 15,
      faceoffWinPct: 0.57142,
      gameWinningGoals: 1,
      gamesPlayed: 27,
      goals: 9,
      lastName: "Batherson",
      otGoals: 0,
      penaltyMinutes: 10,
      playerId: 8480208,
      plusMinus: -1,
      points: 28,
      pointsPerGame: 1.03703,
      positionCode: "R",
      ppGoals: 5,
      ppPoints: 13,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.15254,
      shootsCatches: "R",
      shots: 59,
      skaterFullName: "Drake Batherson",
      teamAbbrevs: "OTT",
      timeOnIcePerGame: 1104.9259,
    },
    {
      assists: 12,
      evGoals: 10,
      evPoints: 15,
      faceoffWinPct: 0.55795,
      gameWinningGoals: 2,
      gamesPlayed: 31,
      goals: 15,
      lastName: "Hischier",
      otGoals: 0,
      penaltyMinutes: 2,
      playerId: 8480002,
      plusMinus: 10,
      points: 27,
      pointsPerGame: 0.87096,
      positionCode: "C",
      ppGoals: 5,
      ppPoints: 11,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 1,
      shootingPct: 0.17241,
      shootsCatches: "L",
      shots: 87,
      skaterFullName: "Nico Hischier",
      teamAbbrevs: "NJD",
      timeOnIcePerGame: 1226.1935,
    },
    {
      assists: 15,
      evGoals: 11,
      evPoints: 21,
      faceoffWinPct: 0.33333,
      gameWinningGoals: 3,
      gamesPlayed: 26,
      goals: 12,
      lastName: "Marchment",
      otGoals: 0,
      penaltyMinutes: 27,
      playerId: 8478975,
      plusMinus: 15,
      points: 27,
      pointsPerGame: 1.03846,
      positionCode: "L",
      ppGoals: 1,
      ppPoints: 6,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.19047,
      shootsCatches: "L",
      shots: 63,
      skaterFullName: "Mason Marchment",
      teamAbbrevs: "DAL",
      timeOnIcePerGame: 948.5384,
    },
    {
      assists: 16,
      evGoals: 6,
      evPoints: 15,
      faceoffWinPct: 0.48148,
      gameWinningGoals: 3,
      gamesPlayed: 27,
      goals: 11,
      lastName: "Michkov",
      otGoals: 3,
      penaltyMinutes: 28,
      playerId: 8484387,
      plusMinus: 5,
      points: 27,
      pointsPerGame: 1.0,
      positionCode: "R",
      ppGoals: 5,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.21153,
      shootsCatches: "L",
      shots: 52,
      skaterFullName: "Matvei Michkov",
      teamAbbrevs: "PHI",
      timeOnIcePerGame: 1023.1111,
    },
    {
      assists: 17,
      evGoals: 10,
      evPoints: 20,
      faceoffWinPct: 0.375,
      gameWinningGoals: 0,
      gamesPlayed: 28,
      goals: 10,
      lastName: "Marchenko",
      otGoals: 0,
      penaltyMinutes: 10,
      playerId: 8480893,
      plusMinus: 11,
      points: 27,
      pointsPerGame: 0.96428,
      positionCode: "R",
      ppGoals: 0,
      ppPoints: 7,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.14705,
      shootsCatches: "R",
      shots: 68,
      skaterFullName: "Kirill Marchenko",
      teamAbbrevs: "CBJ",
      timeOnIcePerGame: 1080.6428,
    },
    {
      assists: 19,
      evGoals: 5,
      evPoints: 19,
      faceoffWinPct: 0.58286,
      gameWinningGoals: 3,
      gamesPlayed: 30,
      goals: 8,
      lastName: "Crosby",
      otGoals: 2,
      penaltyMinutes: 17,
      playerId: 8471675,
      plusMinus: -7,
      points: 27,
      pointsPerGame: 0.9,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 8,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.08988,
      shootsCatches: "L",
      shots: 89,
      skaterFullName: "Sidney Crosby",
      teamAbbrevs: "PIT",
      timeOnIcePerGame: 1211.5333,
    },
    {
      assists: 25,
      evGoals: 1,
      evPoints: 15,
      faceoffWinPct: null,
      gameWinningGoals: 0,
      gamesPlayed: 30,
      goals: 2,
      lastName: "Morrissey",
      otGoals: 0,
      penaltyMinutes: 16,
      playerId: 8477504,
      plusMinus: 2,
      points: 27,
      pointsPerGame: 0.9,
      positionCode: "D",
      ppGoals: 1,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.03225,
      shootsCatches: "L",
      shots: 62,
      skaterFullName: "Josh Morrissey",
      teamAbbrevs: "WPG",
      timeOnIcePerGame: 1479.6,
    },
    {
      assists: 11,
      evGoals: 12,
      evPoints: 19,
      faceoffWinPct: 0.5,
      gameWinningGoals: 4,
      gamesPlayed: 27,
      goals: 15,
      lastName: "McMichael",
      otGoals: 0,
      penaltyMinutes: 10,
      playerId: 8481580,
      plusMinus: 10,
      points: 26,
      pointsPerGame: 0.96296,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 6,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 1,
      shootingPct: 0.18987,
      shootsCatches: "L",
      shots: 79,
      skaterFullName: "Connor McMichael",
      teamAbbrevs: "WSH",
      timeOnIcePerGame: 1072.1481,
    },
    {
      assists: 13,
      evGoals: 8,
      evPoints: 19,
      faceoffWinPct: 0.54098,
      gameWinningGoals: 1,
      gamesPlayed: 26,
      goals: 13,
      lastName: "Guentzel",
      otGoals: 0,
      penaltyMinutes: 8,
      playerId: 8477404,
      plusMinus: 6,
      points: 26,
      pointsPerGame: 1.0,
      positionCode: "C",
      ppGoals: 5,
      ppPoints: 7,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.18055,
      shootsCatches: "L",
      shots: 72,
      skaterFullName: "Jake Guentzel",
      teamAbbrevs: "TBL",
      timeOnIcePerGame: 1234.1923,
    },
    {
      assists: 13,
      evGoals: 10,
      evPoints: 20,
      faceoffWinPct: 0.45219,
      gameWinningGoals: 1,
      gamesPlayed: 28,
      goals: 13,
      lastName: "Bennett",
      otGoals: 0,
      penaltyMinutes: 39,
      playerId: 8477935,
      plusMinus: -3,
      points: 26,
      pointsPerGame: 0.92857,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 6,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.15853,
      shootsCatches: "L",
      shots: 82,
      skaterFullName: "Sam Bennett",
      teamAbbrevs: "FLA",
      timeOnIcePerGame: 1030.7857,
    },
    {
      assists: 17,
      evGoals: 6,
      evPoints: 18,
      faceoffWinPct: 0.30434,
      gameWinningGoals: 2,
      gamesPlayed: 28,
      goals: 9,
      lastName: "Keller",
      otGoals: 1,
      penaltyMinutes: 12,
      playerId: 8479343,
      plusMinus: -1,
      points: 26,
      pointsPerGame: 0.92857,
      positionCode: "R",
      ppGoals: 3,
      ppPoints: 8,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.13235,
      shootsCatches: "L",
      shots: 68,
      skaterFullName: "Clayton Keller",
      teamAbbrevs: "UTA",
      timeOnIcePerGame: 1136.9285,
    },
    {
      assists: 18,
      evGoals: 4,
      evPoints: 18,
      faceoffWinPct: 0.44868,
      gameWinningGoals: 0,
      gamesPlayed: 27,
      goals: 8,
      lastName: "Pettersson",
      otGoals: 0,
      penaltyMinutes: 10,
      playerId: 8480012,
      plusMinus: 0,
      points: 26,
      pointsPerGame: 0.96296,
      positionCode: "C",
      ppGoals: 4,
      ppPoints: 8,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.15094,
      shootsCatches: "L",
      shots: 53,
      skaterFullName: "Elias Pettersson",
      teamAbbrevs: "VAN",
      timeOnIcePerGame: 1183.1111,
    },
    {
      assists: 8,
      evGoals: 10,
      evPoints: 17,
      faceoffWinPct: 0.5,
      gameWinningGoals: 3,
      gamesPlayed: 28,
      goals: 17,
      lastName: "Caufield",
      otGoals: 0,
      penaltyMinutes: 4,
      playerId: 8481540,
      plusMinus: -3,
      points: 25,
      pointsPerGame: 0.89285,
      positionCode: "R",
      ppGoals: 7,
      ppPoints: 8,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.22077,
      shootsCatches: "R",
      shots: 77,
      skaterFullName: "Cole Caufield",
      teamAbbrevs: "MTL",
      timeOnIcePerGame: 1064.3214,
    },
    {
      assists: 10,
      evGoals: 11,
      evPoints: 18,
      faceoffWinPct: null,
      gameWinningGoals: 3,
      gamesPlayed: 18,
      goals: 15,
      lastName: "Ovechkin",
      otGoals: 0,
      penaltyMinutes: 8,
      playerId: 8471214,
      plusMinus: 15,
      points: 25,
      pointsPerGame: 1.38888,
      positionCode: "L",
      ppGoals: 4,
      ppPoints: 7,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.23809,
      shootsCatches: "R",
      shots: 63,
      skaterFullName: "Alex Ovechkin",
      teamAbbrevs: "WSH",
      timeOnIcePerGame: 1056.2222,
    },
    {
      assists: 15,
      evGoals: 6,
      evPoints: 13,
      faceoffWinPct: 0.33333,
      gameWinningGoals: 2,
      gamesPlayed: 28,
      goals: 10,
      lastName: "Guenther",
      otGoals: 1,
      penaltyMinutes: 14,
      playerId: 8482699,
      plusMinus: 9,
      points: 25,
      pointsPerGame: 0.89285,
      positionCode: "R",
      ppGoals: 4,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.15384,
      shootsCatches: "R",
      shots: 65,
      skaterFullName: "Dylan Guenther",
      teamAbbrevs: "UTA",
      timeOnIcePerGame: 974.25,
    },
    {
      assists: 16,
      evGoals: 6,
      evPoints: 17,
      faceoffWinPct: 0.28571,
      gameWinningGoals: 1,
      gamesPlayed: 24,
      goals: 9,
      lastName: "Ehlers",
      otGoals: 1,
      penaltyMinutes: 2,
      playerId: 8477940,
      plusMinus: 5,
      points: 25,
      pointsPerGame: 1.04166,
      positionCode: "L",
      ppGoals: 3,
      ppPoints: 8,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.14754,
      shootsCatches: "L",
      shots: 61,
      skaterFullName: "Nikolaj Ehlers",
      teamAbbrevs: "WPG",
      timeOnIcePerGame: 932.9583,
    },
    {
      assists: 17,
      evGoals: 5,
      evPoints: 16,
      faceoffWinPct: 0.5,
      gameWinningGoals: 2,
      gamesPlayed: 27,
      goals: 8,
      lastName: "Garland",
      otGoals: 1,
      penaltyMinutes: 15,
      playerId: 8478856,
      plusMinus: 5,
      points: 25,
      pointsPerGame: 0.92592,
      positionCode: "R",
      ppGoals: 3,
      ppPoints: 9,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.13559,
      shootsCatches: "R",
      shots: 59,
      skaterFullName: "Conor Garland",
      teamAbbrevs: "VAN",
      timeOnIcePerGame: 1177.4074,
    },
    {
      assists: 19,
      evGoals: 5,
      evPoints: 18,
      faceoffWinPct: 0.44032,
      gameWinningGoals: 1,
      gamesPlayed: 30,
      goals: 6,
      lastName: "Malkin",
      otGoals: 0,
      penaltyMinutes: 14,
      playerId: 8471215,
      plusMinus: -13,
      points: 25,
      pointsPerGame: 0.83333,
      positionCode: "C",
      ppGoals: 1,
      ppPoints: 7,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.09836,
      shootsCatches: "L",
      shots: 61,
      skaterFullName: "Evgeni Malkin",
      teamAbbrevs: "PIT",
      timeOnIcePerGame: 1128.9,
    },
    {
      assists: 19,
      evGoals: 2,
      evPoints: 8,
      faceoffWinPct: null,
      gameWinningGoals: 0,
      gamesPlayed: 28,
      goals: 6,
      lastName: "Gostisbehere",
      otGoals: 0,
      penaltyMinutes: 16,
      playerId: 8476906,
      plusMinus: -6,
      points: 25,
      pointsPerGame: 0.89285,
      positionCode: "D",
      ppGoals: 4,
      ppPoints: 17,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.10909,
      shootsCatches: "L",
      shots: 55,
      skaterFullName: "Shayne Gostisbehere",
      teamAbbrevs: "CAR",
      timeOnIcePerGame: 1139.1071,
    },
    {
      assists: 21,
      evGoals: 3,
      evPoints: 13,
      faceoffWinPct: null,
      gameWinningGoals: 1,
      gamesPlayed: 26,
      goals: 4,
      lastName: "Hedman",
      otGoals: 0,
      penaltyMinutes: 10,
      playerId: 8475167,
      plusMinus: 4,
      points: 25,
      pointsPerGame: 0.96153,
      positionCode: "D",
      ppGoals: 1,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.0625,
      shootsCatches: "L",
      shots: 64,
      skaterFullName: "Victor Hedman",
      teamAbbrevs: "TBL",
      timeOnIcePerGame: 1400.6923,
    },
    {
      assists: 11,
      evGoals: 10,
      evPoints: 19,
      faceoffWinPct: 0.4,
      gameWinningGoals: 1,
      gamesPlayed: 30,
      goals: 13,
      lastName: "Lee",
      otGoals: 0,
      penaltyMinutes: 12,
      playerId: 8475314,
      plusMinus: 4,
      points: 24,
      pointsPerGame: 0.8,
      positionCode: "L",
      ppGoals: 3,
      ppPoints: 5,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.13978,
      shootsCatches: "L",
      shots: 93,
      skaterFullName: "Anders Lee",
      teamAbbrevs: "NYI",
      timeOnIcePerGame: 1033.7666,
    },
    {
      assists: 13,
      evGoals: 9,
      evPoints: 20,
      faceoffWinPct: 0.51573,
      gameWinningGoals: 0,
      gamesPlayed: 25,
      goals: 11,
      lastName: "Cirelli",
      otGoals: 0,
      penaltyMinutes: 12,
      playerId: 8478519,
      plusMinus: 14,
      points: 24,
      pointsPerGame: 0.96,
      positionCode: "C",
      ppGoals: 1,
      ppPoints: 2,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 2,
      shootingPct: 0.20754,
      shootsCatches: "L",
      shots: 53,
      skaterFullName: "Anthony Cirelli",
      teamAbbrevs: "TBL",
      timeOnIcePerGame: 1121.68,
    },
    {
      assists: 13,
      evGoals: 4,
      evPoints: 11,
      faceoffWinPct: 0.5,
      gameWinningGoals: 0,
      gamesPlayed: 28,
      goals: 11,
      lastName: "Svechnikov",
      otGoals: 0,
      penaltyMinutes: 28,
      playerId: 8480830,
      plusMinus: -4,
      points: 24,
      pointsPerGame: 0.85714,
      positionCode: "R",
      ppGoals: 7,
      ppPoints: 13,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.11827,
      shootsCatches: "L",
      shots: 93,
      skaterFullName: "Andrei Svechnikov",
      teamAbbrevs: "CAR",
      timeOnIcePerGame: 1061.9285,
    },
    {
      assists: 14,
      evGoals: 8,
      evPoints: 19,
      faceoffWinPct: 0.33333,
      gameWinningGoals: 1,
      gamesPlayed: 30,
      goals: 10,
      lastName: "McCann",
      otGoals: 1,
      penaltyMinutes: 2,
      playerId: 8477955,
      plusMinus: 6,
      points: 24,
      pointsPerGame: 0.8,
      positionCode: "L",
      ppGoals: 2,
      ppPoints: 5,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.1282,
      shootsCatches: "L",
      shots: 78,
      skaterFullName: "Jared McCann",
      teamAbbrevs: "SEA",
      timeOnIcePerGame: 1069.8,
    },
    {
      assists: 14,
      evGoals: 8,
      evPoints: 18,
      faceoffWinPct: 0.30769,
      gameWinningGoals: 2,
      gamesPlayed: 29,
      goals: 10,
      lastName: "Kyrou",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8479385,
      plusMinus: 2,
      points: 24,
      pointsPerGame: 0.82758,
      positionCode: "C",
      ppGoals: 2,
      ppPoints: 6,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.11764,
      shootsCatches: "R",
      shots: 85,
      skaterFullName: "Jordan Kyrou",
      teamAbbrevs: "STL",
      timeOnIcePerGame: 1080.1724,
    },
    {
      assists: 14,
      evGoals: 8,
      evPoints: 19,
      faceoffWinPct: 0.49333,
      gameWinningGoals: 1,
      gamesPlayed: 28,
      goals: 10,
      lastName: "Rossi",
      otGoals: 0,
      penaltyMinutes: 12,
      playerId: 8482079,
      plusMinus: 12,
      points: 24,
      pointsPerGame: 0.85714,
      positionCode: "C",
      ppGoals: 2,
      ppPoints: 5,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.20408,
      shootsCatches: "L",
      shots: 49,
      skaterFullName: "Marco Rossi",
      teamAbbrevs: "MIN",
      timeOnIcePerGame: 1023.9642,
    },
    {
      assists: 15,
      evGoals: 6,
      evPoints: 20,
      faceoffWinPct: 0.52869,
      gameWinningGoals: 0,
      gamesPlayed: 28,
      goals: 9,
      lastName: "Monahan",
      otGoals: 0,
      penaltyMinutes: 14,
      playerId: 8477497,
      plusMinus: 12,
      points: 24,
      pointsPerGame: 0.85714,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 3,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 1,
      shootingPct: 0.12328,
      shootsCatches: "L",
      shots: 73,
      skaterFullName: "Sean Monahan",
      teamAbbrevs: "CBJ",
      timeOnIcePerGame: 1137.7857,
    },
    {
      assists: 15,
      evGoals: 8,
      evPoints: 23,
      faceoffWinPct: 0.22222,
      gameWinningGoals: 2,
      gamesPlayed: 27,
      goals: 9,
      lastName: "Protas",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8481656,
      plusMinus: 12,
      points: 24,
      pointsPerGame: 0.88888,
      positionCode: "C",
      ppGoals: 0,
      ppPoints: 0,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 1,
      shootingPct: 0.19565,
      shootsCatches: "L",
      shots: 46,
      skaterFullName: "Aliaksei Protas",
      teamAbbrevs: "WSH",
      timeOnIcePerGame: 909.2592,
    },
    {
      assists: 16,
      evGoals: 5,
      evPoints: 17,
      faceoffWinPct: 0.4299,
      gameWinningGoals: 1,
      gamesPlayed: 28,
      goals: 8,
      lastName: "Tuch",
      otGoals: 0,
      penaltyMinutes: 15,
      playerId: 8477949,
      plusMinus: 7,
      points: 24,
      pointsPerGame: 0.85714,
      positionCode: "R",
      ppGoals: 0,
      ppPoints: 4,
      seasonId: 20242025,
      shGoals: 3,
      shPoints: 3,
      shootingPct: 0.11764,
      shootsCatches: "R",
      shots: 68,
      skaterFullName: "Alex Tuch",
      teamAbbrevs: "BUF",
      timeOnIcePerGame: 1208.5714,
    },
    {
      assists: 19,
      evGoals: 2,
      evPoints: 17,
      faceoffWinPct: 0.25,
      gameWinningGoals: 1,
      gamesPlayed: 30,
      goals: 5,
      lastName: "Eklund",
      otGoals: 1,
      penaltyMinutes: 2,
      playerId: 8482667,
      plusMinus: -1,
      points: 24,
      pointsPerGame: 0.8,
      positionCode: "L",
      ppGoals: 3,
      ppPoints: 6,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 1,
      shootingPct: 0.10204,
      shootsCatches: "L",
      shots: 49,
      skaterFullName: "William Eklund",
      teamAbbrevs: "SJS",
      timeOnIcePerGame: 1215.3333,
    },
    {
      assists: 20,
      evGoals: 2,
      evPoints: 15,
      faceoffWinPct: null,
      gameWinningGoals: 1,
      gamesPlayed: 30,
      goals: 4,
      lastName: "Pionk",
      otGoals: 0,
      penaltyMinutes: 22,
      playerId: 8480145,
      plusMinus: 8,
      points: 24,
      pointsPerGame: 0.8,
      positionCode: "D",
      ppGoals: 2,
      ppPoints: 8,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 1,
      shootingPct: 0.07272,
      shootsCatches: "R",
      shots: 55,
      skaterFullName: "Neal Pionk",
      teamAbbrevs: "WPG",
      timeOnIcePerGame: 1306.1,
    },
    {
      assists: 11,
      evGoals: 9,
      evPoints: 19,
      faceoffWinPct: 0.56623,
      gameWinningGoals: 5,
      gamesPlayed: 27,
      goals: 12,
      lastName: "Tavares",
      otGoals: 1,
      penaltyMinutes: 16,
      playerId: 8475166,
      plusMinus: 4,
      points: 23,
      pointsPerGame: 0.85185,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 4,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.13186,
      shootsCatches: "L",
      shots: 91,
      skaterFullName: "John Tavares",
      teamAbbrevs: "TOR",
      timeOnIcePerGame: 1087.5185,
    },
    {
      assists: 11,
      evGoals: 6,
      evPoints: 14,
      faceoffWinPct: 0.56706,
      gameWinningGoals: 2,
      gamesPlayed: 28,
      goals: 12,
      lastName: "Larkin",
      otGoals: 0,
      penaltyMinutes: 20,
      playerId: 8477946,
      plusMinus: -1,
      points: 23,
      pointsPerGame: 0.82142,
      positionCode: "C",
      ppGoals: 6,
      ppPoints: 9,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.16216,
      shootsCatches: "L",
      shots: 74,
      skaterFullName: "Dylan Larkin",
      teamAbbrevs: "DET",
      timeOnIcePerGame: 1223.0357,
    },
    {
      assists: 11,
      evGoals: 6,
      evPoints: 12,
      faceoffWinPct: 0.375,
      gameWinningGoals: 0,
      gamesPlayed: 28,
      goals: 12,
      lastName: "DeBrincat",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8479337,
      plusMinus: -6,
      points: 23,
      pointsPerGame: 0.82142,
      positionCode: "R",
      ppGoals: 6,
      ppPoints: 11,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.16,
      shootsCatches: "R",
      shots: 75,
      skaterFullName: "Alex DeBrincat",
      teamAbbrevs: "DET",
      timeOnIcePerGame: 1058.2142,
    },
    {
      assists: 12,
      evGoals: 9,
      evPoints: 17,
      faceoffWinPct: 0.38461,
      gameWinningGoals: 1,
      gamesPlayed: 30,
      goals: 11,
      lastName: "Palmieri",
      otGoals: 0,
      penaltyMinutes: 10,
      playerId: 8475151,
      plusMinus: -3,
      points: 23,
      pointsPerGame: 0.76666,
      positionCode: "C",
      ppGoals: 2,
      ppPoints: 5,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 1,
      shootingPct: 0.15714,
      shootsCatches: "R",
      shots: 70,
      skaterFullName: "Kyle Palmieri",
      teamAbbrevs: "NYI",
      timeOnIcePerGame: 1132.3,
    },
    {
      assists: 15,
      evGoals: 5,
      evPoints: 12,
      faceoffWinPct: 0.36363,
      gameWinningGoals: 2,
      gamesPlayed: 29,
      goals: 8,
      lastName: "Verhaeghe",
      otGoals: 0,
      penaltyMinutes: 20,
      playerId: 8477409,
      plusMinus: -16,
      points: 23,
      pointsPerGame: 0.7931,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 11,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.08421,
      shootsCatches: "L",
      shots: 95,
      skaterFullName: "Carter Verhaeghe",
      teamAbbrevs: "FLA",
      timeOnIcePerGame: 1117.3103,
    },
    {
      assists: 16,
      evGoals: 6,
      evPoints: 13,
      faceoffWinPct: null,
      gameWinningGoals: 1,
      gamesPlayed: 29,
      goals: 7,
      lastName: "Josi",
      otGoals: 0,
      penaltyMinutes: 8,
      playerId: 8474600,
      plusMinus: -21,
      points: 23,
      pointsPerGame: 0.7931,
      positionCode: "D",
      ppGoals: 1,
      ppPoints: 10,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.08139,
      shootsCatches: "L",
      shots: 86,
      skaterFullName: "Roman Josi",
      teamAbbrevs: "NSH",
      timeOnIcePerGame: 1498.7931,
    },
    {
      assists: 7,
      evGoals: 13,
      evPoints: 17,
      faceoffWinPct: 0.4129,
      gameWinningGoals: 1,
      gamesPlayed: 23,
      goals: 15,
      lastName: "Thompson",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8479420,
      plusMinus: 1,
      points: 22,
      pointsPerGame: 0.95652,
      positionCode: "C",
      ppGoals: 2,
      ppPoints: 5,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.1948,
      shootsCatches: "R",
      shots: 77,
      skaterFullName: "Tage Thompson",
      teamAbbrevs: "BUF",
      timeOnIcePerGame: 1131.2608,
    },
    {
      assists: 9,
      evGoals: 7,
      evPoints: 13,
      faceoffWinPct: 0.55555,
      gameWinningGoals: 2,
      gamesPlayed: 31,
      goals: 13,
      lastName: "Noesen",
      otGoals: 0,
      penaltyMinutes: 15,
      playerId: 8476474,
      plusMinus: -2,
      points: 22,
      pointsPerGame: 0.70967,
      positionCode: "R",
      ppGoals: 6,
      ppPoints: 9,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.2,
      shootsCatches: "R",
      shots: 65,
      skaterFullName: "Stefan Noesen",
      teamAbbrevs: "NJD",
      timeOnIcePerGame: 936.0322,
    },
    {
      assists: 9,
      evGoals: 8,
      evPoints: 15,
      faceoffWinPct: 0.2,
      gameWinningGoals: 2,
      gamesPlayed: 27,
      goals: 13,
      lastName: "DeBrusk",
      otGoals: 1,
      penaltyMinutes: 10,
      playerId: 8478498,
      plusMinus: 3,
      points: 22,
      pointsPerGame: 0.81481,
      positionCode: "L",
      ppGoals: 5,
      ppPoints: 7,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.2,
      shootsCatches: "L",
      shots: 65,
      skaterFullName: "Jake DeBrusk",
      teamAbbrevs: "VAN",
      timeOnIcePerGame: 1022.3703,
    },
    {
      assists: 10,
      evGoals: 8,
      evPoints: 14,
      faceoffWinPct: 0.54716,
      gameWinningGoals: 2,
      gamesPlayed: 30,
      goals: 12,
      lastName: "Vilardi",
      otGoals: 0,
      penaltyMinutes: 4,
      playerId: 8480014,
      plusMinus: 2,
      points: 22,
      pointsPerGame: 0.73333,
      positionCode: "C",
      ppGoals: 4,
      ppPoints: 8,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.21052,
      shootsCatches: "R",
      shots: 57,
      skaterFullName: "Gabriel Vilardi",
      teamAbbrevs: "WPG",
      timeOnIcePerGame: 1116.0333,
    },
    {
      assists: 11,
      evGoals: 10,
      evPoints: 15,
      faceoffWinPct: 0.42857,
      gameWinningGoals: 4,
      gamesPlayed: 30,
      goals: 11,
      lastName: "Marchand",
      otGoals: 2,
      penaltyMinutes: 26,
      playerId: 8473419,
      plusMinus: -3,
      points: 22,
      pointsPerGame: 0.73333,
      positionCode: "L",
      ppGoals: 1,
      ppPoints: 7,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.1279,
      shootsCatches: "L",
      shots: 86,
      skaterFullName: "Brad Marchand",
      teamAbbrevs: "BOS",
      timeOnIcePerGame: 1114.0666,
    },
    {
      assists: 11,
      evGoals: 7,
      evPoints: 15,
      faceoffWinPct: 0.25,
      gameWinningGoals: 3,
      gamesPlayed: 27,
      goals: 11,
      lastName: "Wilson",
      otGoals: 1,
      penaltyMinutes: 28,
      playerId: 8476880,
      plusMinus: 6,
      points: 22,
      pointsPerGame: 0.81481,
      positionCode: "R",
      ppGoals: 4,
      ppPoints: 6,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 1,
      shootingPct: 0.17741,
      shootsCatches: "R",
      shots: 62,
      skaterFullName: "Tom Wilson",
      teamAbbrevs: "WSH",
      timeOnIcePerGame: 1113.6666,
    },
    {
      assists: 12,
      evGoals: 9,
      evPoints: 20,
      faceoffWinPct: 0.27272,
      gameWinningGoals: 1,
      gamesPlayed: 27,
      goals: 10,
      lastName: "Cuylle",
      otGoals: 0,
      penaltyMinutes: 14,
      playerId: 8482157,
      plusMinus: 11,
      points: 22,
      pointsPerGame: 0.81481,
      positionCode: "L",
      ppGoals: 0,
      ppPoints: 1,
      seasonId: 20242025,
      shGoals: 1,
      shPoints: 1,
      shootingPct: 0.2,
      shootsCatches: "L",
      shots: 50,
      skaterFullName: "Will Cuylle",
      teamAbbrevs: "NYR",
      timeOnIcePerGame: 879.5555,
    },
    {
      assists: 15,
      evGoals: 5,
      evPoints: 17,
      faceoffWinPct: 0.4521,
      gameWinningGoals: 1,
      gamesPlayed: 28,
      goals: 7,
      lastName: "Cooley",
      otGoals: 0,
      penaltyMinutes: 12,
      playerId: 8483431,
      plusMinus: 9,
      points: 22,
      pointsPerGame: 0.78571,
      positionCode: "C",
      ppGoals: 2,
      ppPoints: 5,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.12068,
      shootsCatches: "L",
      shots: 58,
      skaterFullName: "Logan Cooley",
      teamAbbrevs: "UTA",
      timeOnIcePerGame: 984.5,
    },
    {
      assists: 16,
      evGoals: 4,
      evPoints: 13,
      faceoffWinPct: null,
      gameWinningGoals: 1,
      gamesPlayed: 14,
      goals: 6,
      lastName: "Stone",
      otGoals: 0,
      penaltyMinutes: 0,
      playerId: 8475913,
      plusMinus: 8,
      points: 22,
      pointsPerGame: 1.57142,
      positionCode: "R",
      ppGoals: 2,
      ppPoints: 9,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.21428,
      shootsCatches: "R",
      shots: 28,
      skaterFullName: "Mark Stone",
      teamAbbrevs: "VGK",
      timeOnIcePerGame: 1148.4285,
    },
    {
      assists: 19,
      evGoals: 3,
      evPoints: 13,
      faceoffWinPct: null,
      gameWinningGoals: 1,
      gamesPlayed: 27,
      goals: 3,
      lastName: "Theodore",
      otGoals: 0,
      penaltyMinutes: 12,
      playerId: 8477447,
      plusMinus: 1,
      points: 22,
      pointsPerGame: 0.81481,
      positionCode: "D",
      ppGoals: 0,
      ppPoints: 9,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.05454,
      shootsCatches: "L",
      shots: 55,
      skaterFullName: "Shea Theodore",
      teamAbbrevs: "VGK",
      timeOnIcePerGame: 1344.0,
    },
    {
      assists: 22,
      evGoals: 0,
      evPoints: 12,
      faceoffWinPct: null,
      gameWinningGoals: 0,
      gamesPlayed: 27,
      goals: 0,
      lastName: "Fox",
      otGoals: 0,
      penaltyMinutes: 16,
      playerId: 8479323,
      plusMinus: 2,
      points: 22,
      pointsPerGame: 0.81481,
      positionCode: "D",
      ppGoals: 0,
      ppPoints: 10,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.0,
      shootsCatches: "R",
      shots: 40,
      skaterFullName: "Adam Fox",
      teamAbbrevs: "NYR",
      timeOnIcePerGame: 1378.8148,
    },
    {
      assists: 9,
      evGoals: 10,
      evPoints: 17,
      faceoffWinPct: 0.41176,
      gameWinningGoals: 4,
      gamesPlayed: 28,
      goals: 12,
      lastName: "Laferriere",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8482155,
      plusMinus: 10,
      points: 21,
      pointsPerGame: 0.75,
      positionCode: "R",
      ppGoals: 2,
      ppPoints: 4,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.20338,
      shootsCatches: "R",
      shots: 59,
      skaterFullName: "Alex Laferriere",
      teamAbbrevs: "LAK",
      timeOnIcePerGame: 961.3214,
    },
    {
      assists: 12,
      evGoals: 2,
      evPoints: 10,
      faceoffWinPct: 0.5873,
      gameWinningGoals: 1,
      gamesPlayed: 28,
      goals: 9,
      lastName: "Hertl",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8476881,
      plusMinus: -8,
      points: 21,
      pointsPerGame: 0.75,
      positionCode: "C",
      ppGoals: 7,
      ppPoints: 11,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.14516,
      shootsCatches: "L",
      shots: 62,
      skaterFullName: "Tomas Hertl",
      teamAbbrevs: "VGK",
      timeOnIcePerGame: 1024.6071,
    },
    {
      assists: 13,
      evGoals: 4,
      evPoints: 14,
      faceoffWinPct: 0.23529,
      gameWinningGoals: 1,
      gamesPlayed: 26,
      goals: 8,
      lastName: "Terry",
      otGoals: 0,
      penaltyMinutes: 2,
      playerId: 8478873,
      plusMinus: -1,
      points: 21,
      pointsPerGame: 0.80769,
      positionCode: "R",
      ppGoals: 4,
      ppPoints: 7,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.11594,
      shootsCatches: "R",
      shots: 69,
      skaterFullName: "Troy Terry",
      teamAbbrevs: "ANA",
      timeOnIcePerGame: 1121.1153,
    },
    {
      assists: 14,
      evGoals: 6,
      evPoints: 19,
      faceoffWinPct: 0.58513,
      gameWinningGoals: 2,
      gamesPlayed: 30,
      goals: 7,
      lastName: "Horvat",
      otGoals: 1,
      penaltyMinutes: 2,
      playerId: 8477500,
      plusMinus: 6,
      points: 21,
      pointsPerGame: 0.7,
      positionCode: "C",
      ppGoals: 1,
      ppPoints: 2,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.08333,
      shootsCatches: "L",
      shots: 84,
      skaterFullName: "Bo Horvat",
      teamAbbrevs: "NYI",
      timeOnIcePerGame: 1219.8666,
    },
    {
      assists: 14,
      evGoals: 6,
      evPoints: 12,
      faceoffWinPct: 0.39719,
      gameWinningGoals: 1,
      gamesPlayed: 30,
      goals: 7,
      lastName: "Mittelstadt",
      otGoals: 0,
      penaltyMinutes: 10,
      playerId: 8479999,
      plusMinus: -15,
      points: 21,
      pointsPerGame: 0.7,
      positionCode: "C",
      ppGoals: 1,
      ppPoints: 9,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.14583,
      shootsCatches: "L",
      shots: 48,
      skaterFullName: "Casey Mittelstadt",
      teamAbbrevs: "COL",
      timeOnIcePerGame: 1121.5333,
    },
    {
      assists: 16,
      evGoals: 1,
      evPoints: 9,
      faceoffWinPct: null,
      gameWinningGoals: 2,
      gamesPlayed: 31,
      goals: 5,
      lastName: "Hamilton",
      otGoals: 0,
      penaltyMinutes: 16,
      playerId: 8476462,
      plusMinus: -1,
      points: 21,
      pointsPerGame: 0.67741,
      positionCode: "D",
      ppGoals: 4,
      ppPoints: 12,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.05208,
      shootsCatches: "R",
      shots: 96,
      skaterFullName: "Dougie Hamilton",
      teamAbbrevs: "NJD",
      timeOnIcePerGame: 1237.4516,
    },
    {
      assists: 16,
      evGoals: 3,
      evPoints: 10,
      faceoffWinPct: 0.30952,
      gameWinningGoals: 2,
      gamesPlayed: 28,
      goals: 5,
      lastName: "Bedard",
      otGoals: 0,
      penaltyMinutes: 12,
      playerId: 8484144,
      plusMinus: -12,
      points: 21,
      pointsPerGame: 0.75,
      positionCode: "C",
      ppGoals: 2,
      ppPoints: 11,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.07246,
      shootsCatches: "R",
      shots: 69,
      skaterFullName: "Connor Bedard",
      teamAbbrevs: "CHI",
      timeOnIcePerGame: 1171.2142,
    },
    {
      assists: 17,
      evGoals: 3,
      evPoints: 16,
      faceoffWinPct: 0.48611,
      gameWinningGoals: 1,
      gamesPlayed: 28,
      goals: 4,
      lastName: "Schmaltz",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8477951,
      plusMinus: -4,
      points: 21,
      pointsPerGame: 0.75,
      positionCode: "C",
      ppGoals: 1,
      ppPoints: 5,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.0625,
      shootsCatches: "R",
      shots: 64,
      skaterFullName: "Nick Schmaltz",
      teamAbbrevs: "UTA",
      timeOnIcePerGame: 1114.5,
    },
    {
      assists: 11,
      evGoals: 6,
      evPoints: 17,
      faceoffWinPct: 0.52095,
      gameWinningGoals: 2,
      gamesPlayed: 19,
      goals: 9,
      lastName: "Seguin",
      otGoals: 0,
      penaltyMinutes: 2,
      playerId: 8475794,
      plusMinus: 14,
      points: 20,
      pointsPerGame: 1.05263,
      positionCode: "C",
      ppGoals: 3,
      ppPoints: 3,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.2093,
      shootsCatches: "R",
      shots: 43,
      skaterFullName: "Tyler Seguin",
      teamAbbrevs: "DAL",
      timeOnIcePerGame: 973.2105,
    },
    {
      assists: 11,
      evGoals: 7,
      evPoints: 16,
      faceoffWinPct: 0.5,
      gameWinningGoals: 0,
      gamesPlayed: 29,
      goals: 9,
      lastName: "Bjorkstrand",
      otGoals: 0,
      penaltyMinutes: 4,
      playerId: 8477416,
      plusMinus: 5,
      points: 20,
      pointsPerGame: 0.68965,
      positionCode: "R",
      ppGoals: 2,
      ppPoints: 4,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.14062,
      shootsCatches: "R",
      shots: 64,
      skaterFullName: "Oliver Bjorkstrand",
      teamAbbrevs: "SEA",
      timeOnIcePerGame: 924.7586,
    },
    {
      assists: 11,
      evGoals: 7,
      evPoints: 15,
      faceoffWinPct: 0.375,
      gameWinningGoals: 2,
      gamesPlayed: 30,
      goals: 9,
      lastName: "Meier",
      otGoals: 0,
      penaltyMinutes: 29,
      playerId: 8478414,
      plusMinus: 6,
      points: 20,
      pointsPerGame: 0.66666,
      positionCode: "R",
      ppGoals: 2,
      ppPoints: 5,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.0909,
      shootsCatches: "L",
      shots: 99,
      skaterFullName: "Timo Meier",
      teamAbbrevs: "NJD",
      timeOnIcePerGame: 1029.8,
    },
    {
      assists: 11,
      evGoals: 7,
      evPoints: 17,
      faceoffWinPct: 0.7,
      gameWinningGoals: 0,
      gamesPlayed: 31,
      goals: 9,
      lastName: "Zetterlund",
      otGoals: 0,
      penaltyMinutes: 6,
      playerId: 8480188,
      plusMinus: 6,
      points: 20,
      pointsPerGame: 0.64516,
      positionCode: "L",
      ppGoals: 2,
      ppPoints: 3,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.13636,
      shootsCatches: "R",
      shots: 66,
      skaterFullName: "Fabian Zetterlund",
      teamAbbrevs: "SJS",
      timeOnIcePerGame: 1048.3548,
    },
    {
      assists: 11,
      evGoals: 7,
      evPoints: 18,
      faceoffWinPct: 0.5,
      gameWinningGoals: 2,
      gamesPlayed: 27,
      goals: 9,
      lastName: "LafreniÃ¨re",
      otGoals: 0,
      penaltyMinutes: 4,
      playerId: 8482109,
      plusMinus: -11,
      points: 20,
      pointsPerGame: 0.74074,
      positionCode: "L",
      ppGoals: 2,
      ppPoints: 2,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.15254,
      shootsCatches: "L",
      shots: 59,
      skaterFullName: "Alexis LafreniÃ¨re",
      teamAbbrevs: "NYR",
      timeOnIcePerGame: 1051.4074,
    },
    {
      assists: 13,
      evGoals: 4,
      evPoints: 13,
      faceoffWinPct: 0.5,
      gameWinningGoals: 1,
      gamesPlayed: 28,
      goals: 7,
      lastName: "Zucker",
      otGoals: 0,
      penaltyMinutes: 29,
      playerId: 8475722,
      plusMinus: 4,
      points: 20,
      pointsPerGame: 0.71428,
      positionCode: "L",
      ppGoals: 3,
      ppPoints: 7,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.14285,
      shootsCatches: "L",
      shots: 49,
      skaterFullName: "Jason Zucker",
      teamAbbrevs: "BUF",
      timeOnIcePerGame: 917.25,
    },
    {
      assists: 13,
      evGoals: 5,
      evPoints: 13,
      faceoffWinPct: null,
      gameWinningGoals: 2,
      gamesPlayed: 28,
      goals: 7,
      lastName: "Sergachev",
      otGoals: 1,
      penaltyMinutes: 16,
      playerId: 8479410,
      plusMinus: 5,
      points: 20,
      pointsPerGame: 0.71428,
      positionCode: "D",
      ppGoals: 2,
      ppPoints: 7,
      seasonId: 20242025,
      shGoals: 0,
      shPoints: 0,
      shootingPct: 0.15217,
      shootsCatches: "L",
      shots: 46,
      skaterFullName: "Mikhail Sergachev",
      teamAbbrevs: "UTA",
      timeOnIcePerGame: 1527.6428,
    },
  ],
  total: 770,
};
