export interface Player {
  id: number;
  name: string;
  points: number;
  goals: number;
  assists: number;
  timeOnIce: number;
  fights: number;
}

export const fakePlayers: Player[] = [
  {
    id: 1,
    name: "Sydney Crosby",
    points: 50,
    goals: 5,
    assists: 30,
    timeOnIce: 20,
    fights: 5,
  },
  {
    id: 2,
    name: "Conor Bedard",
    points: 70,
    goals: 5,
    assists: 40,
    timeOnIce: 25,
    fights: 2,
  },
  {
    id: 3,
    name: "Nick Suzuki",
    points: 10,
    goals: 5,
    assists: 10,
    timeOnIce: 18,
    fights: 1,
  },
  {
    id: 4,
    name: "Ryan Reeves",
    points: 60,
    goals: 5,
    assists: 35,
    timeOnIce: 22,
    fights: 1,
  },
  {
    id: 5,
    name: "Ryan Donato",
    points: 80,
    goals: 5,
    assists: 50,
    timeOnIce: 30,
    fights: 0,
  },
  {
    id: 6,
    name: "Ryan Suter",
    points: 45,
    goals: 5,
    assists: 25,
    timeOnIce: 19,
    fights: 0,
  },
  {
    id: 7,
    name: "Jake Fox",
    points: 35,
    goals: 15,
    assists: 20,
    timeOnIce: 18,
    fights: 2,
  },
  {
    id: 8,
    name: "Liam Torres",
    points: 42,
    goals: 20,
    assists: 22,
    timeOnIce: 17,
    fights: 1,
  },
  {
    id: 9,
    name: "Aiden Lee",
    points: 51,
    goals: 23,
    assists: 28,
    timeOnIce: 20,
    fights: 3,
  },
  {
    id: 10,
    name: "Noah Brown",
    points: 27,
    goals: 10,
    assists: 17,
    timeOnIce: 15,
    fights: 0,
  },
  {
    id: 11,
    name: "Ethan Taylor",
    points: 39,
    goals: 16,
    assists: 23,
    timeOnIce: 19,
    fights: 1,
  },
  {
    id: 12,
    name: "Caleb Wilson",
    points: 48,
    goals: 22,
    assists: 26,
    timeOnIce: 21,
    fights: 0,
  },
  {
    id: 13,
    name: "Oliver Martinez",
    points: 44,
    goals: 18,
    assists: 26,
    timeOnIce: 18,
    fights: 2,
  },
  {
    id: 14,
    name: "Oliver Davis",
    points: 55,
    goals: 25,
    assists: 30,
    timeOnIce: 22,
    fights: 1,
  },
  {
    id: 15,
    name: "Benjamin Scott",
    points: 31,
    goals: 13,
    assists: 18,
    timeOnIce: 16,
    fights: 1,
  },
  {
    id: 16,
    name: "Elijah Allen",
    points: 49,
    goals: 21,
    assists: 28,
    timeOnIce: 20,
    fights: 0,
  },
  {
    id: 17,
    name: "Lucas Thomas",
    points: 36,
    goals: 14,
    assists: 22,
    timeOnIce: 18,
    fights: 1,
  },
  {
    id: 18,
    name: "William Moore",
    points: 38,
    goals: 19,
    assists: 19,
    timeOnIce: 17,
    fights: 2,
  },
  {
    id: 19,
    name: "James King",
    points: 40,
    goals: 20,
    assists: 20,
    timeOnIce: 19,
    fights: 0,
  },
  {
    id: 20,
    name: "Ryan Robinson",
    points: 28,
    goals: 12,
    assists: 16,
    timeOnIce: 16,
    fights: 1,
  },
  {
    id: 21,
    name: "Alexander Perez",
    points: 33,
    goals: 15,
    assists: 18,
    timeOnIce: 17,
    fights: 0,
  },
  {
    id: 22,
    name: "Mason Carter",
    points: 54,
    goals: 26,
    assists: 28,
    timeOnIce: 21,
    fights: 2,
  },
  {
    id: 23,
    name: "Ryan Mitchell",
    points: 37,
    goals: 16,
    assists: 21,
    timeOnIce: 18,
    fights: 1,
  },
  {
    id: 24,
    name: "Jayden Ramirez",
    points: 41,
    goals: 22,
    assists: 19,
    timeOnIce: 19,
    fights: 3,
  },
  {
    id: 25,
    name: "Matthew Hill",
    points: 29,
    goals: 12,
    assists: 17,
    timeOnIce: 16,
    fights: 0,
  },
  {
    id: 26,
    name: "Ryan Gonzalez",
    points: 52,
    goals: 24,
    assists: 28,
    timeOnIce: 21,
    fights: 1,
  },
  {
    id: 27,
    name: "Joseph Clark",
    points: 34,
    goals: 13,
    assists: 21,
    timeOnIce: 17,
    fights: 2,
  },
  {
    id: 28,
    name: "Jackson Lewis",
    points: 43,
    goals: 20,
    assists: 23,
    timeOnIce: 19,
    fights: 1,
  },
  {
    id: 29,
    name: "James Walker",
    points: 39,
    goals: 18,
    assists: 21,
    timeOnIce: 18,
    fights: 0,
  },
  {
    id: 30,
    name: "Ryan Young",
    points: 56,
    goals: 29,
    assists: 27,
    timeOnIce: 22,
    fights: 3,
  },
  {
    id: 31,
    name: "John Harris",
    points: 32,
    goals: 14,
    assists: 18,
    timeOnIce: 16,
    fights: 1,
  },
  {
    id: 32,
    name: "Anthony Hall",
    points: 50,
    goals: 24,
    assists: 26,
    timeOnIce: 21,
    fights: 2,
  },
  {
    id: 33,
    name: "Ryan Lewis",
    points: 47,
    goals: 22,
    assists: 25,
    timeOnIce: 20,
    fights: 1,
  },
  {
    id: 34,
    name: "Joshua Rodriguez",
    points: 30,
    goals: 12,
    assists: 18,
    timeOnIce: 17,
    fights: 0,
  },
  {
    id: 35,
    name: "Janik Green",
    points: 53,
    goals: 27,
    assists: 26,
    timeOnIce: 22,
    fights: 3,
  },
  {
    id: 36,
    name: "Ryan White",
    points: 46,
    goals: 21,
    assists: 25,
    timeOnIce: 20,
    fights: 2,
  },
];
