export const makinnon = {
  gameLog: [
    {
      gameId: 2024020447,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-12-10",
      goals: 1,
      assists: 4,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Penguins",
      },
      points: 5,
      plusMinus: 4,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 3,
      shifts: 20,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "PIT",
      pim: 0,
      toi: "17:36",
    },
    {
      gameId: 2024020440,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-12-08",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Devils",
      },
      points: 0,
      plusMinus: 0,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 6,
      shifts: 20,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "NJD",
      pim: 0,
      toi: "21:46",
    },
    {
      gameId: 2024020432,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-12-07",
      goals: 0,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Red Wings",
      },
      points: 1,
      plusMinus: -1,
      powerPlayGoals: 0,
      powerPlayPoints: 1,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 2,
      shifts: 25,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "DET",
      pim: 0,
      toi: "22:47",
    },
    {
      gameId: 2024020415,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-12-05",
      goals: 0,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Hurricanes",
      },
      points: 1,
      plusMinus: 0,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 3,
      shifts: 22,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "CAR",
      pim: 0,
      toi: "25:05",
    },
    {
      gameId: 2024020397,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-12-03",
      goals: 2,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Sabres",
      },
      points: 3,
      plusMinus: 1,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 9,
      shifts: 26,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "BUF",
      pim: 0,
      toi: "23:33",
    },
    {
      gameId: 2024020385,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-11-30",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Oilers",
      },
      points: 0,
      plusMinus: -2,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 7,
      shifts: 23,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "EDM",
      pim: 0,
      toi: "23:29",
    },
    {
      gameId: 2024020373,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-11-29",
      goals: 0,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Stars",
      },
      points: 1,
      plusMinus: -1,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 5,
      shifts: 23,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "DAL",
      pim: 0,
      toi: "26:02",
    },
    {
      gameId: 2024020358,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-11-27",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Golden Knights",
      },
      points: 0,
      plusMinus: 1,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 10,
      shifts: 28,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "VGK",
      pim: 0,
      toi: "27:05",
    },
    {
      gameId: 2024020334,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-11-25",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Lightning",
      },
      points: 0,
      plusMinus: -3,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 0,
      shifts: 22,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "TBL",
      pim: 0,
      toi: "21:51",
    },
    {
      gameId: 2024020321,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-11-23",
      goals: 0,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Panthers",
      },
      points: 1,
      plusMinus: 3,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 2,
      shifts: 25,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "FLA",
      pim: 0,
      toi: "22:24",
    },
    {
      gameId: 2024020310,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-11-21",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Capitals",
      },
      points: 0,
      plusMinus: 0,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 3,
      shifts: 21,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "WSH",
      pim: 0,
      toi: "22:16",
    },
    {
      gameId: 2024020289,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-11-18",
      goals: 0,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Flyers",
      },
      points: 1,
      plusMinus: 0,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 2,
      shifts: 27,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "PHI",
      pim: 6,
      toi: "22:39",
    },
    {
      gameId: 2024020268,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-11-15",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Capitals",
      },
      points: 0,
      plusMinus: -2,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 0,
      shifts: 24,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "WSH",
      pim: 0,
      toi: "22:06",
    },
    {
      gameId: 2024020255,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-11-13",
      goals: 0,
      assists: 3,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Kings",
      },
      points: 3,
      plusMinus: 3,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 3,
      shifts: 27,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "LAK",
      pim: 0,
      toi: "24:45",
    },
    {
      gameId: 2024020243,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-11-11",
      goals: 0,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Predators",
      },
      points: 1,
      plusMinus: 1,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 5,
      shifts: 30,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "NSH",
      pim: 0,
      toi: "24:29",
    },
    {
      gameId: 2024020233,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-11-09",
      goals: 1,
      assists: 3,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Hurricanes",
      },
      points: 4,
      plusMinus: 3,
      powerPlayGoals: 0,
      powerPlayPoints: 1,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 7,
      shifts: 28,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "CAR",
      pim: 0,
      toi: "26:19",
    },
    {
      gameId: 2024020217,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-11-07",
      goals: 0,
      assists: 0,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Jets",
      },
      points: 0,
      plusMinus: 0,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 4,
      shifts: 27,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "WPG",
      pim: 0,
      toi: "24:29",
    },
    {
      gameId: 2024020202,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-11-05",
      goals: 0,
      assists: 5,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Kraken",
      },
      points: 5,
      plusMinus: 3,
      powerPlayGoals: 0,
      powerPlayPoints: 2,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 4,
      shifts: 24,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "SEA",
      pim: 0,
      toi: "24:21",
    },
    {
      gameId: 2024020182,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-11-02",
      goals: 1,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Predators",
      },
      points: 2,
      plusMinus: -1,
      powerPlayGoals: 0,
      powerPlayPoints: 1,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 6,
      shifts: 29,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "NSH",
      pim: 0,
      toi: "22:32",
    },
    {
      gameId: 2024020157,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-10-30",
      goals: 0,
      assists: 2,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Lightning",
      },
      points: 2,
      plusMinus: 0,
      powerPlayGoals: 0,
      powerPlayPoints: 1,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 2,
      shifts: 25,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "TBL",
      pim: 0,
      toi: "24:58",
    },
    {
      gameId: 2024020144,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-10-28",
      goals: 1,
      assists: 0,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Blackhawks",
      },
      points: 1,
      plusMinus: -4,
      powerPlayGoals: 1,
      powerPlayPoints: 1,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 1,
      shifts: 25,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "CHI",
      pim: 0,
      toi: "24:57",
    },
    {
      gameId: 2024020139,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-10-27",
      goals: 1,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Senators",
        fr: "Sénateurs",
      },
      points: 2,
      plusMinus: 1,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 1,
      otGoals: 0,
      shots: 5,
      shifts: 27,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "OTT",
      pim: 0,
      toi: "23:14",
    },
    {
      gameId: 2024020115,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-10-24",
      goals: 0,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Utah Hockey Club",
        fr: "Club de hockey de l'Utah",
      },
      points: 1,
      plusMinus: 1,
      powerPlayGoals: 0,
      powerPlayPoints: 1,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 3,
      shifts: 22,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "UTA",
      pim: 0,
      toi: "20:57",
    },
    {
      gameId: 2024020106,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-10-22",
      goals: 1,
      assists: 0,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Kraken",
      },
      points: 1,
      plusMinus: 0,
      powerPlayGoals: 1,
      powerPlayPoints: 1,
      gameWinningGoals: 1,
      otGoals: 0,
      shots: 2,
      shifts: 26,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "SEA",
      pim: 0,
      toi: "21:51",
    },
    {
      gameId: 2024020089,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-10-20",
      goals: 0,
      assists: 2,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Sharks",
      },
      points: 2,
      plusMinus: 2,
      powerPlayGoals: 0,
      powerPlayPoints: 1,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 3,
      shifts: 23,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "SJS",
      pim: 0,
      toi: "20:00",
    },
    {
      gameId: 2024020074,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-10-18",
      goals: 1,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Ducks",
      },
      points: 2,
      plusMinus: 1,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 1,
      otGoals: 1,
      shots: 9,
      shifts: 28,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "ANA",
      pim: 2,
      toi: "23:48",
    },
    {
      gameId: 2024020059,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-10-16",
      goals: 0,
      assists: 2,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Bruins",
      },
      points: 2,
      plusMinus: -2,
      powerPlayGoals: 0,
      powerPlayPoints: 2,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 1,
      shifts: 28,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "BOS",
      pim: 0,
      toi: "23:48",
    },
    {
      gameId: 2024020047,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-10-14",
      goals: 0,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Islanders",
      },
      points: 1,
      plusMinus: -3,
      powerPlayGoals: 0,
      powerPlayPoints: 0,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 5,
      shifts: 28,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "NYI",
      pim: 0,
      toi: "23:00",
    },
    {
      gameId: 2024020034,
      teamAbbrev: "COL",
      homeRoadFlag: "H",
      gameDate: "2024-10-12",
      goals: 1,
      assists: 1,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Blue Jackets",
      },
      points: 2,
      plusMinus: 1,
      powerPlayGoals: 1,
      powerPlayPoints: 1,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 3,
      shifts: 25,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "CBJ",
      pim: 10,
      toi: "23:23",
    },
    {
      gameId: 2024020010,
      teamAbbrev: "COL",
      homeRoadFlag: "R",
      gameDate: "2024-10-09",
      goals: 0,
      assists: 2,
      commonName: {
        default: "Avalanche",
      },
      opponentCommonName: {
        default: "Golden Knights",
      },
      points: 2,
      plusMinus: -2,
      powerPlayGoals: 0,
      powerPlayPoints: 1,
      gameWinningGoals: 0,
      otGoals: 0,
      shots: 4,
      shifts: 23,
      shorthandedGoals: 0,
      shorthandedPoints: 0,
      opponentAbbrev: "VGK",
      pim: 0,
      toi: "21:33",
    },
  ],
};
